import './Image.stories.jsx'
import './Gradient.stories.jsx'
import './Text.stories.jsx'
import './CustomDraw.stories.jsx'
import './Heatmap.stories.jsx'
import './CSS.stories.jsx'
import './Events.stories.jsx'
